import sh
import os
print("Starting...")
print("switched to following dir ")
os.chdir("/home/tulpar/workplace/blog/content/")
print(os.system("pwd"))
print("pulling content from remote origin only_en ....")
os.system("git pull origin master")
os.system("git checkout only_en")
os.system("git pull origin only_en")
print("pulling output from remote origin master....")
os.chdir("/home/tulpar/workplace/blog/output/")
os.system("git pull origin master")
os.system("cp /home/tulpar/workplace/blog/work_dir/*.md /home/tulpar/workplace/blog/content/")
print("copied *.md from work_dir to content")
print("pushing content to remote origin only_en ...")
os.system("git add .")
os.system("git commit -m 'By script'")
os.system("git push origin only_en")
print("20")
print("switched to following dir ")
os.chdir("/home/tulpar/docker/")
print(os.system("pwd"))
os.system('docker run -it -v /home/tulpar/workplace/blog/content/:/home/tulpar/blog_new/blog/content -v /home/tulpar/workplace/blog/output/:/home/tulpar/blog_new/blog/output/ tulpar008/blog:latest /bin/bash -c "cd /home/tulpar/blog_new/blog/;make html"')
print("switched to following dir ")
os.chdir("/home/tulpar/workplace/blog/output/")
print(os.system("pwd"))
print("pushing output to remote origin master....")
os.system("git add .")
os.system("git commit -m 'By script'")
os.system("git push origin master")
